### ISSUE TITLE
Need documentation for "actionable" remote notifications

### ISSUE THREAD

**Issue by andrewhavens** [infinitered/ProMotion-push#6]
I see that support for "actionable" remote notifications was added in #4, but no documentation was added. I'm reading through the code, trying to understand what I need to do to support this feature, but I'm confused about how the callback mechanism is supposed to work.

@BananaNeil @squidpunch @jamonholmgren Could either of you point me in the right direction? If you could provide a code sample, I could update the readme.

**Comment by andrewhavens** [comment]
I came across more information about actionable notifications: https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/IPhoneOSClientImp.html#//apple_ref/doc/uid/TP40008194-CH103-SW26

They are different than I thought they were, so I'm not planning on using them. At some point, it would be nice to add docs for this, but it's not critical at the moment.

**Comment by jamonholmgren** [comment]
Cool, if you can contribute docs at some point @andrewhavens that would be awesome.

**Comment by dchersey** [comment]
on it ...
